### ISSUE TITLE
Unable to view anything flash related

### ISSUE THREAD

**Issue by eazar001** [k0ral/hbro#17]
Flash animations, youtube videos, nothing works. I'm sure it's documented, but I can't for the life of me find out how to use flash with `hbro`. Some enlightenment would be greatly appreciated. I'm using version 1.5 and i'm using the default `ui.xml`. Is there anything else you need to know?

**Comment by eazar001** [comment]
Never mind, I see I need to enable plugins with a custom configuration file.

**Comment by k0ral** [comment]
Indeed, it's disabled by default as it sometimes makes the browser crash :/ .
You can enable plugins like this:

```
s <- getWebSettings
set s webSettingsEnablePlugins True
```

Note that there's an extended configuration file example in the `hbro-contrib` package.

**Comment by eazar001** [comment]
Thanks, the configuration file worked, but for some odd reason the browser is still not detecting the plugin. Perhaps this is system specific, but it seems to be detected on my other browsers.

While on the topic of configuration however, is it not a viable idea to make a non "ghc-compiling" style of configuration. I undersand applications like `xmonad` get away with this, but only because they pull in a very small amount of dependencies. Yours however, appears to pull in a significantly greater amount. Given that in Haskell, cabal hell is always lurking about, perhaps it might be better to implement a configuration system independent of registered packages?

I haven't programmed in Haskell for quite some time, so perhaps I'm no longer in the know. I usually like to build my application in a sandbox and install them globally while avoiding registering packages to ghc. This way I keep my system as clean as possible.

**Comment by k0ral** [comment]
I agree that pulling a lot of dependencies is annoying, especially in Haskell. However, I have 2 reasons not to do otherwise:
- using another configuration language (e.g. Lua) will require a significant amount of binding code, and will probably have some limitations;
- removing some dependencies would have me handwriting their equivalent, probably in a less generic/portable/maintainable way.

I definitely acknowledge that it hinders the usability of the project, but IMHO the right place for a viable solution is where the root cause lies, ie in the package management system.
That being said, if you have a specific suggestion about how to reduce the dependencies, I'll be happy to discuss it :) .

**Comment by eazar001** [comment]
I see; fair points. I'll definitely keep this in mind, and if I have any recommendations, I'll be sure to bring them up.
